### PR TITLE
Option added: Keep only sequences starting with methionine and ending with a stop codon

### PR DESCRIPTION
**Pull request by yaiza612**
As done in Dominique Koua, Anicet Ebou & Sébastien Dutertre (2021), ConoDictor will now support the custom parameter of keeping only sequences starting with methionine and ending with a stop codon. 
This filtering is always done in ConoSorter when the input file is a DNA fasta file after the translation. 
If you would want to do this filtering in ConoDictor, you would need to directly provide an already filtered peptide fasta file. 
 With this new option, the filtering can be done automatically taking only 3% longer. 
The implementation is backwards compatible as the default argument will not change the behaviour. Additionally, there is a message if the user provides a DNA fasta file and the filtering is not turn on.

### CODE REVIEW

**Comment by yaiza612** [comment]
I know that sometimes you can filter out good sequences, but for that reason it is just an option that you can choose to set to true or not, and the filtering would work with the protein fasta file or DNA fasta file (once it is translated). 
I programmed it anyways for doing the same steps of the paper Dominique Koua, Anicet Ebou & Sébastien Dutertre (2021) (section 3.4) so the time invested in the pull request was the time in adding the argument and write the pull request. 
(sorry for closing and reopening the pull requests, they were misclicks )

**Comment by yaiza612** [comment]
> I know that sometimes you can filter out good sequences, but for that reason it is just an option that you can choose to set to true or not, and the filtering would work with the protein fasta file or DNA fasta file. I programmed it anyways for doing the same steps of the paper Dominique Koua, Anicet Ebou & Sébastien Dutertre (2021) (section 3.4) so the time invested in the pull request was the time in adding the argument and write the pull request.

**Comment by Ebedthan** [comment]
Ok, I see. But I do not understand what you mean by " doing the same steps of the paper Dominique Koua, Anicet Ebou & Sébastien Dutertre (2021)". The current implementation is the same we have used in the paper, except we have turned off the filtering which was done not as you did but by filtering out the predictions which were done only on the signal or propeptide region.

Anyway, let me go through the PR and see if I can merge it right away

**Comment by yaiza612** [comment]
"We ran ConoDictor 2.0 using custom parameters to fit conditions used by Dutertre et al.: we kept only sequences starting with methionine and ending with a stop codon, with a minimum read length of 50 bp, considered a minimum number of read occurrences of 2." This is the approach I'm referring to, and the paper of Dutertre (Dutertre S. et al.  (2014)) that is cited is using ConoSorter and ConoSorter did the filtering before applying anything else so I thought that was the approach. Maybe I misunderstood this step. 
Maybe we can have a VC meeting with me and my supervisor (Thomas Suply) to clarify this, as it is easier to discuss in that way?

**Comment by Ebedthan** [comment]
Great! Okay. I understand what you are saying. I will review the PR and see if we can add this option.
We are always happy to discuss, although I do not see the necessity here if related to this PR. Anyway if you want us to collaborate on some exciting project we are always open, you can find using our mail on the paper (if sending the mail, please do not forget to add Dominique Koua and Sebastien Dutertre in CC).

**Pull request closed without merging**
